### ISSUE TITLE
怎么安装使用？

### ISSUE THREAD

**Issue by makelove** [yaleimeng/py3Aiml_Chinese#1]
麻烦完善一下文档，好吗？

能不能pip安装？
或者setup.py

测试一下，cn-test.aiml 没法用。

Alice请您提问... >>你好？
WARNING: No match found for input: 你 好 ？
Alice请您提问... >>天气
WARNING: No match found for input: 天 气

**Comment by yaleimeng** [comment]
感谢您的提问。
当初通过git 命令行上传的 *aiml文件* 不知为何，有些异常，一直没发现。现已做内容更新，自测能够**正常读取并响应**。
请您用最新aiml脚本试一下。欢迎加星，提改进意见。
