### ISSUE TITLE
用start获取*的内容怎么都有空格？这个问题怎么解决？

### ISSUE THREAD

**Issue by 645187919** [yaleimeng/py3Aiml_Chinese#2]

**Comment by yaleimeng** [comment]
1，还请贴出一个实例来看一下。
2，有空格的原因应该是系统在内部处理时每个字之间都加了空格。想去除的话直接replace(' ','')就解决了。

**Comment by 645187919** [comment]
给个邮箱呗，我直接把效果图发给你。在这里应该没法贴图吧？

**Comment by 645187919** [comment]
输入：小明笨
<category>
<pattern>*笨</pattern>
<template>很抱歉让您失望了。我会加油学习，天天向上的。<star/></template>
</category>
运行效果：很抱歉让您失望了。我会加油学习，天天向上的。小 明

**Comment by 645187919** [comment]
输入：小明笨
`<category>
<pattern>*笨</pattern>
<template>很抱歉让您失望了。我会加油学习，天天向上的。<star/></template>
</category>`
效果：很抱歉让您失望了。我会加油学习，天天向上的。小 明

**Comment by 645187919** [comment]
我想解决的问题是如何通过System标签运行python命令，然后在Args中利用*来得到对应的输入句子，但是运行您的案例却只能得到一个汉字。案例如下：
`<category>
  <pattern>* </pattern>
  <template>
    
    <system>python test.py <star/></system>
  </template>`
test.py：
`if __name__ == '__main__':
    # os.kill(simple.py)
    print("hello world")
    print(sys.argv[1])`
输入：发生发的是
输出：hello world  发
输入：sfaf
输出：hello world  sfaf
所以还是由于输出的语句含有空格的问题，不过可以尝试其他的途径解决我的问题。但是您能否更改下对应的源码来解决这个问题？

**Comment by yaleimeng** [comment]
抱歉没明白您输出一下**hello world + 原来的句子**这是想干什么。。即便在英文模式下，用sys.argv本来也只能获得1个单词，因为空格会将参数中断。
关于本项目的使用请参考Example里面的示例。高级一点的话，在项目的基础上还可以做web站点的搭建，做成一个服务器对外提供应答。

**Comment by HIT-Owen** [comment]
我也发现了类似的问题，输出的文字之间会有空格，暂时先用replace(' ', '')来处理吧
