### ISSUE TITLE
srai中文问题

### ISSUE THREAD

**Issue by li-shilong** [yaleimeng/py3Aiml_Chinese#4]
pattern标签自动将中文添加空格，然而sria没有自动添加空格，导致无法匹配。
目前手工把sria文字添加空格可以匹配，或者sria使用英文也可以匹配。能否添加sria自动分割中文

**Comment by yaleimeng** [comment]
已在Kernel文件中添加了<srai>分割处理语句。您可以试一下是否生效。

**Comment by li-shilong** [comment]
此问题已解决，非常感谢。
