### ISSUE TITLE
<pattern>标签不支持特殊符号

### ISSUE THREAD

**Issue by li-shilong** [yaleimeng/py3Aiml_Chinese#5]
在<pattern>标签中使用 / （） 等符号 无法匹配，不知这个问题是否能够解决。

Enter your message >> /
WARNING: No match found for input: /

**Comment by yaleimeng** [comment]
您可以先在英文原版aiml中试一下是否同样有此问题。有些特殊字符可能是系统保留字，不允许在模式中出现。我也只能对自己所做的汉化部分做一些细微的工作而已。

**Comment by li-shilong** [comment]
原版也无法解析，还有*号也是无法匹配这些符号的。

**Comment by yaleimeng** [comment]
aiml不支持这样的操作可能有它自身的考虑。建议您积极寻找其他替代方案，比如替换为中文的一些标点符号。
