### ISSUE TITLE
有计划支持 AIML 2.0 吗

### ISSUE THREAD

**Issue by yzhang37** [yaleimeng/py3Aiml_Chinese#7]
这里看到有 https://blog.csdn.net/qin8752/article/details/79386121 ，AIML 2.0 的项目，相比而言增加了 #， condition, loop 等多个功能，但是作者没有开源。

AIML 2.0 的规范是谷歌提供的，是否有增加 2.0 的支持？

**Comment by yaleimeng** [comment]
有段时间没维护AIML这个项目了。
如果不是已经在aiml上投入了很多沉没成本的话，建议尝试RiveScript、ChatScript、Superscript等。脚本编写更容易，匹配功能更灵活，可读性也更好。

**Comment by yzhang37** [comment]
好的。

**Comment by xxllp** [comment]
不知道   RiveScript、ChatScript、Superscript  这几个里面哪个更好用哈
