### ISSUE TITLE
会话sessionID的追踪与退出

### ISSUE THREAD

**Issue by liutianling** [yaleimeng/py3Aiml_Chinese#8]
你好，我这边是想尝试做下个性化的聊天。
假如通过某种方式为每个人设置了会话ID，进入ID后是不是只能匹配这个ID下的规则，这个时候还能匹配一些公共的规则吗，比如问候之类的。
还有就是，进入某个ID后，如何退出这个ID的会话内容，每次怎么自动保存这个ID的会话数据。谢谢！

**Comment by yaleimeng** [comment]
AIML前期并没有考虑个性化聊天的细节。如果要对不同的客户，适用不同的规则（通用+专用），很可能需要运行多个实例，学习不同组合的aiml文件来应对。
aiml好像不存在session退出的问题，因为它响应一句之后，如果不采用循环让它等待输入，工作就完成了。至于保存会话内容，只需要利用IO接口，将相应的输入输出成对地写入文件或数据库即可。

**Comment by liutianling** [comment]
非常感谢，你回答的非常专业，谢谢
