### ISSUE TITLE
不能按相似度匹配

### ISSUE THREAD

**Issue by bigsinger** [yaleimeng/py3Aiml_Chinese#9]
提问：你好
居然匹配不到，一定要提问：你好啊

试了其他关键词也是一样，好像是精准匹配，不能近似匹配，（正则表达式批评和模糊匹配没有一意义，要相似度匹配），请问如何解决

**Comment by yaleimeng** [comment]
在写的规则里面有通配符。具体还是要学习aiml的语法规范，多测试才能达到预期的目的。
amil本身跟正则表达式方式匹配就差不多。虽然有不少局限，但善加利用（特别是英语环境）也是很强的。
至于你要按语义匹配，那跟aiml就没什么关系了。需要继续在知识的海洋里多学习了。

**Comment by bigsinger** [comment]
> 在写的规则里面有通配符。具体还是要学习aiml的语法规范，多测试才能达到预期的目的。
> amil本身跟正则表达式方式匹配就差不多。虽然有不少局限，但善加利用（特别是英语环境）也是很强的。
> 至于你要按语义匹配，那跟aiml就没什么关系了。需要继续在知识的海洋里多学习了。

原来是正则表达式的方式，明白了
